<?php
/**
 * FineArtPhotographer.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace RK\FineArtPhotographerModule\Helper;

use RK\FineArtPhotographerModule\Helper\Base\AbstractTranslatableHelper;

/**
 * Helper implementation class for translatable methods.
 */
class TranslatableHelper extends AbstractTranslatableHelper
{
    // feel free to add your own convenience methods here
}
