services:
    # Form field types
    
    rk_fineartphotographer_module.form.type.field.multilist:
        class: RK\FineArtPhotographerModule\Form\Type\Field\MultiListType
        arguments:
            - "@rk_fineartphotographer_module.listentries_helper"
        tags:
            - { name: form.type }
    
    rk_fineartphotographer_module.form.type.field.translation:
        class: RK\FineArtPhotographerModule\Form\Type\Field\TranslationType
        tags:
            - { name: form.type }
    
    rk_fineartphotographer_module.form.type.field.upload:
        class: RK\FineArtPhotographerModule\Form\Type\Field\UploadType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@rk_fineartphotographer_module.image_helper"
            - "@rk_fineartphotographer_module.upload_helper"
        tags:
            - { name: form.type }
