rkfineartphotographermodule:
    # define routing support for these controllers
    resource: "@RKFineArtPhotographerModule/Controller"
    # enable support for defining routes by annotations
    type: annotation
