services:
    # Custom validators
    rk_fineartphotographer_module.validator.list_entry.validator:
        class: RK\FineArtPhotographerModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@rk_fineartphotographer_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: rk_fineartphotographer_module.validator.list_entry.validator }
