<?php
/**
 * FineArtPhotographer.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace RK\FineArtPhotographerModule;

use RK\FineArtPhotographerModule\Base\AbstractFineArtPhotographerEvents;

/**
 * Events definition implementation class.
 */
class FineArtPhotographerEvents extends AbstractFineArtPhotographerEvents
{
    // feel free to extend the events definition here
}
