<?php
/**
 * FineArtPhotographer.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace RK\FineArtPhotographerModule;

use RK\FineArtPhotographerModule\Base\AbstractRKFineArtPhotographerModule;

/**
 * Module implementation class.
 */
class RKFineArtPhotographerModule extends AbstractRKFineArtPhotographerModule
{
    // custom enhancements can go here
}
