<?php
/**
 * FineArtPhotographer.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace RK\FineArtPhotographerModule\Form\Type\Hook;

use RK\FineArtPhotographerModule\Form\Type\Hook\Base\AbstractEditAlbumType;

/**
 * Edit album form type implementation class.
 */
class EditAlbumType extends AbstractEditAlbumType
{
    // feel free to extend the base form type class here
}
