<?php
/**
 * FineArtPhotographer.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace RK\FineArtPhotographerModule\Entity;

use RK\FineArtPhotographerModule\Entity\Base\AbstractHookAssignmentEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Entity implementation class for hooked object assignments.
 *
 * @ORM\Entity()
 * @ORM\Table(name="rk_faph_hookassignment")
 */
class HookAssignmentEntity extends AbstractHookAssignmentEntity
{
    // feel free to add your own methods here
}
