<?php
/**
 * FineArtPhotographer.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace RK\FineArtPhotographerModule\DependencyInjection;

use RK\FineArtPhotographerModule\DependencyInjection\Base\AbstractRKFineArtPhotographerExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class RKFineArtPhotographerExtension extends AbstractRKFineArtPhotographerExtension
{
    // custom enhancements can go here
}
