<?php
/**
 * FineArtPhotographer.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace RK\FineArtPhotographerModule\HookSubscriber;

use RK\FineArtPhotographerModule\HookSubscriber\Base\AbstractAlbumUiHooksSubscriber;

/**
 * Implementation class for ui hooks subscriber.
 */
class AlbumUiHooksSubscriber extends AbstractAlbumUiHooksSubscriber
{
    // feel free to add your own convenience methods here
}
