<?php
/**
 * FineArtPhotographer.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\FineArtPhotographerModule\HookProvider;

use RK\FineArtPhotographerModule\HookProvider\Base\AbstractAlbumUiHooksProvider;

/**
 * Implementation class for ui hooks provider.
 */
class AlbumUiHooksProvider extends AbstractAlbumUiHooksProvider
{
    // feel free to add your own convenience methods here
}
