<?php
/**
 * FineArtPhotographer.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\FineArtPhotographerModule\Form\EventListener;

use RK\FineArtPhotographerModule\Form\EventListener\Base\AbstractTranslationListener;

/**
 * Translation listener implementation class.
 */
class TranslationListener extends AbstractTranslationListener
{
    // feel free to add your customisation here
}
