<?php
/**
 * FineArtPhotographer.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace RK\FineArtPhotographerModule\Form\DataTransformer;

use RK\FineArtPhotographerModule\Form\DataTransformer\Base\AbstractListFieldTransformer;

/**
 * List field transformer implementation class.
 *
 * This data transformer treats multi-valued list fields.
 */
class ListFieldTransformer extends AbstractListFieldTransformer
{
    // feel free to add your customisation here
}
