<?php
/**
 * FineArtPhotographer.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace RK\FineArtPhotographerModule\Base;

/**
 * Events definition base class.
 */
abstract class AbstractFineArtPhotographerEvents
{
    /**
     * The rkfineartphotographermodule.album_post_load event is thrown when albums
     * are loaded from the database.
     *
     * The event listener receives an
     * RK\FineArtPhotographerModule\Event\FilterAlbumEvent instance.
     *
     * @see RK\FineArtPhotographerModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const ALBUM_POST_LOAD = 'rkfineartphotographermodule.album_post_load';
    
    /**
     * The rkfineartphotographermodule.album_pre_persist event is thrown before a new album
     * is created in the system.
     *
     * The event listener receives an
     * RK\FineArtPhotographerModule\Event\FilterAlbumEvent instance.
     *
     * @see RK\FineArtPhotographerModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const ALBUM_PRE_PERSIST = 'rkfineartphotographermodule.album_pre_persist';
    
    /**
     * The rkfineartphotographermodule.album_post_persist event is thrown after a new album
     * has been created in the system.
     *
     * The event listener receives an
     * RK\FineArtPhotographerModule\Event\FilterAlbumEvent instance.
     *
     * @see RK\FineArtPhotographerModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const ALBUM_POST_PERSIST = 'rkfineartphotographermodule.album_post_persist';
    
    /**
     * The rkfineartphotographermodule.album_pre_remove event is thrown before an existing album
     * is removed from the system.
     *
     * The event listener receives an
     * RK\FineArtPhotographerModule\Event\FilterAlbumEvent instance.
     *
     * @see RK\FineArtPhotographerModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const ALBUM_PRE_REMOVE = 'rkfineartphotographermodule.album_pre_remove';
    
    /**
     * The rkfineartphotographermodule.album_post_remove event is thrown after an existing album
     * has been removed from the system.
     *
     * The event listener receives an
     * RK\FineArtPhotographerModule\Event\FilterAlbumEvent instance.
     *
     * @see RK\FineArtPhotographerModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const ALBUM_POST_REMOVE = 'rkfineartphotographermodule.album_post_remove';
    
    /**
     * The rkfineartphotographermodule.album_pre_update event is thrown before an existing album
     * is updated in the system.
     *
     * The event listener receives an
     * RK\FineArtPhotographerModule\Event\FilterAlbumEvent instance.
     *
     * @see RK\FineArtPhotographerModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const ALBUM_PRE_UPDATE = 'rkfineartphotographermodule.album_pre_update';
    
    /**
     * The rkfineartphotographermodule.album_post_update event is thrown after an existing new album
     * has been updated in the system.
     *
     * The event listener receives an
     * RK\FineArtPhotographerModule\Event\FilterAlbumEvent instance.
     *
     * @see RK\FineArtPhotographerModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const ALBUM_POST_UPDATE = 'rkfineartphotographermodule.album_post_update';
    
    /**
     * The rkfineartphotographermodule.albumitem_post_load event is thrown when album items
     * are loaded from the database.
     *
     * The event listener receives an
     * RK\FineArtPhotographerModule\Event\FilterAlbumItemEvent instance.
     *
     * @see RK\FineArtPhotographerModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const ALBUMITEM_POST_LOAD = 'rkfineartphotographermodule.albumitem_post_load';
    
    /**
     * The rkfineartphotographermodule.albumitem_pre_persist event is thrown before a new album item
     * is created in the system.
     *
     * The event listener receives an
     * RK\FineArtPhotographerModule\Event\FilterAlbumItemEvent instance.
     *
     * @see RK\FineArtPhotographerModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const ALBUMITEM_PRE_PERSIST = 'rkfineartphotographermodule.albumitem_pre_persist';
    
    /**
     * The rkfineartphotographermodule.albumitem_post_persist event is thrown after a new album item
     * has been created in the system.
     *
     * The event listener receives an
     * RK\FineArtPhotographerModule\Event\FilterAlbumItemEvent instance.
     *
     * @see RK\FineArtPhotographerModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const ALBUMITEM_POST_PERSIST = 'rkfineartphotographermodule.albumitem_post_persist';
    
    /**
     * The rkfineartphotographermodule.albumitem_pre_remove event is thrown before an existing album item
     * is removed from the system.
     *
     * The event listener receives an
     * RK\FineArtPhotographerModule\Event\FilterAlbumItemEvent instance.
     *
     * @see RK\FineArtPhotographerModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const ALBUMITEM_PRE_REMOVE = 'rkfineartphotographermodule.albumitem_pre_remove';
    
    /**
     * The rkfineartphotographermodule.albumitem_post_remove event is thrown after an existing album item
     * has been removed from the system.
     *
     * The event listener receives an
     * RK\FineArtPhotographerModule\Event\FilterAlbumItemEvent instance.
     *
     * @see RK\FineArtPhotographerModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const ALBUMITEM_POST_REMOVE = 'rkfineartphotographermodule.albumitem_post_remove';
    
    /**
     * The rkfineartphotographermodule.albumitem_pre_update event is thrown before an existing album item
     * is updated in the system.
     *
     * The event listener receives an
     * RK\FineArtPhotographerModule\Event\FilterAlbumItemEvent instance.
     *
     * @see RK\FineArtPhotographerModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const ALBUMITEM_PRE_UPDATE = 'rkfineartphotographermodule.albumitem_pre_update';
    
    /**
     * The rkfineartphotographermodule.albumitem_post_update event is thrown after an existing new album item
     * has been updated in the system.
     *
     * The event listener receives an
     * RK\FineArtPhotographerModule\Event\FilterAlbumItemEvent instance.
     *
     * @see RK\FineArtPhotographerModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const ALBUMITEM_POST_UPDATE = 'rkfineartphotographermodule.albumitem_post_update';
    
}
