<?php
/**
 * FineArtPhotographer.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace RK\FineArtPhotographerModule\Base;

use Doctrine\DBAL\Connection;
use RuntimeException;
use Zikula\Core\AbstractExtensionInstaller;
use Zikula\CategoriesModule\Entity\CategoryRegistryEntity;

/**
 * Installer base class.
 */
abstract class AbstractFineArtPhotographerModuleInstaller extends AbstractExtensionInstaller
{
    /**
     * Install the RKFineArtPhotographerModule application.
     *
     * @return boolean True on success, or false
     *
     * @throws RuntimeException Thrown if database tables can not be created or another error occurs
     */
    public function install()
    {
        $logger = $this->container->get('logger');
        $userName = $this->container->get('zikula_users_module.current_user')->get('uname');
    
        // Check if upload directories exist and if needed create them
        try {
            $container = $this->container;
            $uploadHelper = new \RK\FineArtPhotographerModule\Helper\UploadHelper(
                $container->get('translator.default'),
                $container->get('filesystem'),
                $container->get('session'),
                $container->get('logger'),
                $container->get('zikula_users_module.current_user'),
                $container->get('zikula_extensions_module.api.variable'),
                $container->getParameter('datadir')
            );
            $uploadHelper->checkAndCreateAllUploadFolders();
        } catch (\Exception $exception) {
            $this->addFlash('error', $exception->getMessage());
            $logger->error('{app}: User {user} could not create upload folders during installation. Error details: {errorMessage}.', ['app' => 'RKFineArtPhotographerModule', 'user' => $userName, 'errorMessage' => $exception->getMessage()]);
        
            return false;
        }
        // create all tables from according entity definitions
        try {
            $this->schemaTool->create($this->listEntityClasses());
        } catch (\Exception $exception) {
            $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $exception->getMessage());
            $logger->error('{app}: Could not create the database tables during installation. Error details: {errorMessage}.', ['app' => 'RKFineArtPhotographerModule', 'errorMessage' => $exception->getMessage()]);
    
            return false;
        }
    
        // set up all our vars with initial values
        $this->setVar('albumEntriesPerPage', 10);
        $this->setVar('linkOwnAlbumsOnAccountPage', true);
        $this->setVar('albumItemEntriesPerPage', 10);
        $this->setVar('linkOwnAlbumItemsOnAccountPage', true);
        $this->setVar('enableShrinkingForAlbumItemImage', false);
        $this->setVar('shrinkWidthAlbumItemImage', 800);
        $this->setVar('shrinkHeightAlbumItemImage', 600);
        $this->setVar('thumbnailModeAlbumItemImage', 'inset');
        $this->setVar('thumbnailWidthAlbumItemImageView', 32);
        $this->setVar('thumbnailHeightAlbumItemImageView', 24);
        $this->setVar('thumbnailWidthAlbumItemImageDisplay', 240);
        $this->setVar('thumbnailHeightAlbumItemImageDisplay', 180);
        $this->setVar('thumbnailWidthAlbumItemImageEdit', 240);
        $this->setVar('thumbnailHeightAlbumItemImageEdit', 180);
        $this->setVar('enabledFinderTypes', 'album###albumItem');
    
        $categoryRegistryIdsPerEntity = [];
    
        // add default entry for category registry (property named Main)
        $categoryHelper = new \RK\FineArtPhotographerModule\Helper\CategoryHelper(
            $this->container->get('translator.default'),
            $this->container->get('request_stack'),
            $logger,
            $this->container->get('zikula_users_module.current_user'),
            $this->container->get('zikula_categories_module.category_registry_repository'),
            $this->container->get('zikula_categories_module.api.category_permission')
        );
        $categoryGlobal = $this->container->get('zikula_categories_module.category_repository')->findOneBy(['name' => 'Global']);
        $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
    
        $registry = new CategoryRegistryEntity();
        $registry->setModname('RKFineArtPhotographerModule');
        $registry->setEntityname('AlbumEntity');
        $registry->setProperty($categoryHelper->getPrimaryProperty('Album'));
        $registry->setCategory($categoryGlobal);
    
        try {
            $entityManager->persist($registry);
            $entityManager->flush();
        } catch (\Exception $exception) {
            $this->addFlash('error', $this->__f('Error! Could not create a category registry for the %entity% entity.', ['%entity%' => 'album']));
            $logger->error('{app}: User {user} could not create a category registry for {entities} during installation. Error details: {errorMessage}.', ['app' => 'RKFineArtPhotographerModule', 'user' => $userName, 'entities' => 'albums', 'errorMessage' => $exception->getMessage()]);
        }
        $categoryRegistryIdsPerEntity['album'] = $registry->getId();
    
        $registry = new CategoryRegistryEntity();
        $registry->setModname('RKFineArtPhotographerModule');
        $registry->setEntityname('AlbumItemEntity');
        $registry->setProperty($categoryHelper->getPrimaryProperty('AlbumItem'));
        $registry->setCategory($categoryGlobal);
    
        try {
            $entityManager->persist($registry);
            $entityManager->flush();
        } catch (\Exception $exception) {
            $this->addFlash('error', $this->__f('Error! Could not create a category registry for the %entity% entity.', ['%entity%' => 'album item']));
            $logger->error('{app}: User {user} could not create a category registry for {entities} during installation. Error details: {errorMessage}.', ['app' => 'RKFineArtPhotographerModule', 'user' => $userName, 'entities' => 'album items', 'errorMessage' => $exception->getMessage()]);
        }
        $categoryRegistryIdsPerEntity['albumItem'] = $registry->getId();
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the RKFineArtPhotographerModule application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables can not be updated
     */
    public function upgrade($oldVersion)
    {
    /*
        $logger = $this->container->get('logger');
    
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case '1.0.0':
                // do something
                // ...
                // update the database schema
                try {
                    $this->schemaTool->update($this->listEntityClasses());
                } catch (\Exception $exception) {
                    $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $exception->getMessage());
                    $logger->error('{app}: Could not update the database tables during the upgrade. Error details: {errorMessage}.', ['app' => 'RKFineArtPhotographerModule', 'errorMessage' => $exception->getMessage()]);
    
                    return false;
                }
        }
    
        // Note there are several helpers available for making migrating your extension from Zikula 1.3 to 1.4 easier.
        // The following convenience methods are each responsible for a single aspect of upgrading to Zikula 1.4.x.
    
        // here is a possible usage example
        // of course 1.2.3 should match the number you used for the last stable 1.3.x module version.
        /* if ($oldVersion = '1.2.3') {
            // rename module for all modvars
            $this->updateModVarsTo14();
            
            // update extension information about this app
            $this->updateExtensionInfoFor14();
            
            // rename existing permission rules
            $this->renamePermissionsFor14();
            
            // rename existing category registries
            $this->renameCategoryRegistriesFor14();
            
            // rename all tables
            $this->renameTablesFor14();
            
            // remove event handler definitions from database
            $this->dropEventHandlersFromDatabase();
            
            // update module name in the hook tables
            $this->updateHookNamesFor14();
            
            // update module name in the workflows table
            $this->updateWorkflowsFor14();
        } * /
    
        // remove obsolete persisted hooks from the database
        //$this->hookApi->uninstallSubscriberHooks($this->bundle->getMetaData());
    */
    
        // update successful
        return true;
    }
    
    /**
     * Renames the module name for variables in the module_vars table.
     */
    protected function updateModVarsTo14()
    {
        $conn = $this->getConnection();
        $conn->update('module_vars', ['modname' => 'RKFineArtPhotographerModule'], ['modname' => 'FineArtPhotographer']);
    }
    
    /**
     * Renames this application in the core's extensions table.
     */
    protected function updateExtensionInfoFor14()
    {
        $conn = $this->getConnection();
        $conn->update('modules', ['name' => 'RKFineArtPhotographerModule', 'directory' => 'RK/FineArtPhotographerModule'], ['name' => 'FineArtPhotographer']);
    }
    
    /**
     * Renames all permission rules stored for this app.
     */
    protected function renamePermissionsFor14()
    {
        $conn = $this->getConnection();
        $componentLength = strlen('FineArtPhotographer') + 1;
    
        $conn->executeQuery("
            UPDATE group_perms
            SET component = CONCAT('RKFineArtPhotographerModule', SUBSTRING(component, $componentLength))
            WHERE component LIKE 'FineArtPhotographer%';
        ");
    }
    
    /**
     * Renames all category registries stored for this app.
     */
    protected function renameCategoryRegistriesFor14()
    {
        $conn = $this->getConnection();
        $componentLength = strlen('FineArtPhotographer') + 1;
    
        $conn->executeQuery("
            UPDATE categories_registry
            SET modname = CONCAT('RKFineArtPhotographerModule', SUBSTRING(modname, $componentLength))
            WHERE modname LIKE 'FineArtPhotographer%';
        ");
    }
    
    /**
     * Renames all (existing) tables of this app.
     */
    protected function renameTablesFor14()
    {
        $conn = $this->getConnection();
    
        $oldPrefix = 'faph_';
        $oldPrefixLength = strlen($oldPrefix);
        $newPrefix = 'rk_faph_';
    
        $sm = $conn->getSchemaManager();
        $tables = $sm->listTables();
        foreach ($tables as $table) {
            $tableName = $table->getName();
            if (substr($tableName, 0, $oldPrefixLength) != $oldPrefix) {
                continue;
            }
    
            $newTableName = str_replace($oldPrefix, $newPrefix, $tableName);
    
            $conn->executeQuery("
                RENAME TABLE $tableName
                TO $newTableName;
            ");
        }
    }
    
    /**
     * Removes event handlers from database as they are now described by service definitions and managed by dependency injection.
     */
    protected function dropEventHandlersFromDatabase()
    {
        \EventUtil::unregisterPersistentModuleHandlers('FineArtPhotographer');
    }
    
    /**
     * Updates the module name in the hook tables.
     */
    protected function updateHookNamesFor14()
    {
        $conn = $this->getConnection();
    
        $conn->update('hook_area', ['owner' => 'RKFineArtPhotographerModule'], ['owner' => 'FineArtPhotographer']);
    
        $componentLength = strlen('subscriber.fineartphotographer') + 1;
        $conn->executeQuery("
            UPDATE hook_area
            SET areaname = CONCAT('subscriber.rkfineartphotographermodule', SUBSTRING(areaname, $componentLength))
            WHERE areaname LIKE 'subscriber.fineartphotographer%';
        ");
    
        $conn->update('hook_binding', ['sowner' => 'RKFineArtPhotographerModule'], ['sowner' => 'FineArtPhotographer']);
    
        $conn->update('hook_runtime', ['sowner' => 'RKFineArtPhotographerModule'], ['sowner' => 'FineArtPhotographer']);
    
        $componentLength = strlen('fineartphotographer') + 1;
        $conn->executeQuery("
            UPDATE hook_runtime
            SET eventname = CONCAT('rkfineartphotographermodule', SUBSTRING(eventname, $componentLength))
            WHERE eventname LIKE 'fineartphotographer%';
        ");
    
        $conn->update('hook_subscriber', ['owner' => 'RKFineArtPhotographerModule'], ['owner' => 'FineArtPhotographer']);
    
        $componentLength = strlen('fineartphotographer') + 1;
        $conn->executeQuery("
            UPDATE hook_subscriber
            SET eventname = CONCAT('rkfineartphotographermodule', SUBSTRING(eventname, $componentLength))
            WHERE eventname LIKE 'fineartphotographer%';
        ");
    }
    
    /**
     * Updates the module name in the workflows table.
     */
    protected function updateWorkflowsFor14()
    {
        $conn = $this->getConnection();
        $conn->update('workflows', ['module' => 'RKFineArtPhotographerModule'], ['module' => 'FineArtPhotographer']);
        $conn->update('workflows', ['obj_table' => 'AlbumEntity'], ['module' => 'RKFineArtPhotographerModule', 'obj_table' => 'album']);
        $conn->update('workflows', ['obj_table' => 'AlbumItemEntity'], ['module' => 'RKFineArtPhotographerModule', 'obj_table' => 'albumItem']);
    }
    
    /**
     * Returns connection to the database.
     *
     * @return Connection the current connection
     */
    protected function getConnection()
    {
        $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
    
        return $entityManager->getConnection();
    }
    
    /**
     * Uninstall RKFineArtPhotographerModule.
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables or stored workflows can not be removed
     */
    public function uninstall()
    {
        $logger = $this->container->get('logger');
    
        try {
            $this->schemaTool->drop($this->listEntityClasses());
        } catch (\Exception $exception) {
            $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $exception->getMessage());
            $logger->error('{app}: Could not remove the database tables during uninstallation. Error details: {errorMessage}.', ['app' => 'RKFineArtPhotographerModule', 'errorMessage' => $exception->getMessage()]);
    
            return false;
        }
    
        // remove all module vars
        $this->delVars();
    
        // remove category registry entries
        $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
        $registries = $this->container->get('zikula_categories_module.category_registry_repository')->findBy(['modname' => 'RKFineArtPhotographerModule']);
        foreach ($registries as $registry) {
            $entityManager->remove($registry);
        }
        $entityManager->flush();
    
        // remind user about upload folders not being deleted
        $uploadPath = $this->container->getParameter('datadir') . '/RKFineArtPhotographerModule/';
        $this->addFlash('status', $this->__f('The upload directories at "%path%" can be removed manually.', ['%path%' => $uploadPath]));
    
        // uninstallation successful
        return true;
    }
    
    /**
     * Build array with all entity classes for RKFineArtPhotographerModule.
     *
     * @return string[] List of class names
     */
    protected function listEntityClasses()
    {
        $classNames = [];
        $classNames[] = 'RK\FineArtPhotographerModule\Entity\AlbumEntity';
        $classNames[] = 'RK\FineArtPhotographerModule\Entity\AlbumTranslationEntity';
        $classNames[] = 'RK\FineArtPhotographerModule\Entity\AlbumCategoryEntity';
        $classNames[] = 'RK\FineArtPhotographerModule\Entity\AlbumItemEntity';
        $classNames[] = 'RK\FineArtPhotographerModule\Entity\AlbumItemTranslationEntity';
        $classNames[] = 'RK\FineArtPhotographerModule\Entity\AlbumItemCategoryEntity';
        $classNames[] = 'RK\FineArtPhotographerModule\Entity\HookAssignmentEntity';
    
        return $classNames;
    }
}
